# Generated by Django 4.2.29 on 2026-04-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_sheets_webhook_url',
            field=models.URLField(blank=True, help_text='Webhook URL for Google Sheets automation (Zapier/Make/AppsScript)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Admin number for WhatsApp lead alerts', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_webhook_url',
            field=models.URLField(blank=True, help_text='Webhook URL for WhatsApp automation (Twilio/Interakt/etc.)'),
        ),
    ]
