# Generated by Django 4.2.29 on 2026-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed information about the event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='early_bird_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for the early bird offer.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='early_bird_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted early bird price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard price. Set to 0 for free events.', max_digits=10),
        ),
    ]
