# Generated by Django 4.2.29 on 2026-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_detailed_description_event_early_bird_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='e.g. CEO, Founder, Lead Sales', max_length=120)),
                ('company', models.CharField(blank=True, help_text='Company name', max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('linkedin_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.speaker'),
        ),
    ]
