# Generated by Django 4.2.29 on 2026-06-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_speaker_event_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brochure',
            field=models.FileField(blank=True, help_text='Upload a PDF brochure for this event.', null=True, upload_to='brochures/'),
        ),
        migrations.CreateModel(
            name='BrochureLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochure_leads', to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
