# Generated by Django 5.2.12 on 2026-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_brochure_brochurelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail shown on the events listing cards. Use a smaller, well-cropped image. Falls back to the main image if empty.', null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Main banner image shown on the event detail page.', null=True, upload_to='events/'),
        ),
    ]
